name: Build Grasshopper Plugin

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest # For a list of available runner types, refer to

    env:
      Main_Solution_Name: Tunny.sln
      Plugin_File_Name: Tunny

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore the Tunny application
        run: msbuild $env:Main_Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Build the Tunny application
        run: msbuild $env:Main_Solution_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}
