name: Build Grasshopper Plugin(Windows)

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
