name: Build Grasshopper Plugin(mac)

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Remove dotnet 9 if exists
        run: |
          if [ -d "$DOTNET_ROOT/sdk/9.0"* ]; then
            rm -rf $DOTNET_ROOT/sdk/9.0*
          fi

      - name: Install required workloads
        run: |
          dotnet workload install macos
          dotnet workload install wasm-tools-net7

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
