name: Build Grasshopper Plugin(mac)

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.406"

      - name: Set dotnet version
        run: |
          dotnet new global.json --sdk-version 8.0.406

      - name: Install required workloads
        run: |
          dotnet workload install macos
          dotnet workload install wasm-tools-net7

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
