name: test and coverage

on: [pull_request]

jobs:
  test:
    name: Test and Check Coverage
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          dotnet restore
          pip install optuna find-libpython

      - name: Set Python DLL path and PYTHONHOME
        run: |
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append -InputObject "PYTHONNET_PYDLL=$(python -m find_libpython)"
          Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append -InputObject "PYTHONHOME=$(python -c 'import sys; print(sys.prefix)')"

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          fail_ci_if_error: true
          token: ${{secrets.CODECOV_TOKEN}}
